// These styles apply to every route in the application
import './globals.css'

export const metadata = {
  title: 'Bruno Empke - Portfólio',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <body className='antialiased'>{children}</body>
    </html>
  )
}